title: Erika Maessaka, UX/UI Designer
email: maessakaerika@gmail.com
description: a UX/UI Designer with an empathic and pragmatic approach to design, translated in user-centred interfaces
baseurl: "/linguagens-final"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  erikamsk

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: none

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path

